# This is a basic workflow to help you get started with Actions





# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the Practica5 branch
  push: 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew        
          ./gradlew build

  Verificacion:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Creando JDK
        uses: actions/setup-java@v1
        with: 
          java-version: 1.7
      - name: Cheks
        run: | 
          chmod +x gradlew        
          ./gradlew check
